### ISSUE TITLE
 install face_recognition 失败了, 有啥建议吗?

### ISSUE THREAD

**Issue by ithjz** [vipstone/faceai#25]
C:\Users\Administrator>pip3 install face_recognition
Collecting face_recognition
  Using cached https://files.pythonhosted.org/packages/3f/ed/ad9a28042f373d4633f
c8b49109b623597d6f193d3bbbef7780a5ee8eef2/face_recognition-1.2.3-py2.py3-none-an
y.whl
Collecting dlib>=19.7 (from face_recognition)
  Using cached https://files.pythonhosted.org/packages/df/aa/6a9bb2a763107bb2606
d6ee1aa65fcd3b51375a9ef6436e9c9280b0dd63c/dlib-19.15.0.tar.gz
Requirement already satisfied: numpy in f:\program files\anaconda3\lib\site-pack
ages (from face_recognition) (1.14.3)
Requirement already satisfied: face-recognition-models>=0.3.0 in f:\program file
s\anaconda3\lib\site-packages (from face_recognition) (0.3.0)
Requirement already satisfied: Click>=6.0 in f:\program files\anaconda3\lib\site
-packages (from face_recognition) (6.6)
Requirement already satisfied: Pillow in f:\program files\anaconda3\lib\site-pac
kages (from face_recognition) (3.3.1)
Building wheels for collected packages: dlib
  Running setup.py bdist_wheel for dlib ... error
  Complete output from command "f:\program files\anaconda3\python.exe" -u -c "im
port setuptools, tokenize;__file__='C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\p
ip-install-z6wr0c9k\\dlib\\setup.py';f=getattr(tokenize, 'open', open)(__file__)
;code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exe
c'))" bdist_wheel -d C:\Users\ADMINI~1\AppData\Local\Temp\pip-wheel-cdrpikq0 --p
ython-tag cp35:
  running bdist_wheel
  running build
  running build_py
  package init file 'dlib\__init__.py' not found (or not a regular file)
  running build_ext
  Traceback (most recent call last):
    File "C:\Users\ADMINI~1\AppData\Local\Temp\pip-install-z6wr0c9k\dlib\setup.p
y", line 118, in get_cmake_version
      out = subprocess.check_output(['cmake', '--version'])
    File "f:\program files\anaconda3\lib\subprocess.py", line 626, in check_outp
ut
      **kwargs).stdout
    File "f:\program files\anaconda3\lib\subprocess.py", line 693, in run
      with Popen(*popenargs, **kwargs) as process:
    File "f:\program files\anaconda3\lib\subprocess.py", line 947, in __init__
      restore_signals, start_new_session)
    File "f:\program files\anaconda3\lib\subprocess.py", line 1224, in _execute_
child
      startupinfo)
  FileNotFoundError: [WinError 2] 系统找不到指定的文件。

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\ADMINI~1\AppData\Local\Temp\pip-install-z6wr0c9k\dlib\setup.p
y", line 257, in <module>
      'Topic :: Software Development',
    File "f:\program files\anaconda3\lib\site-packages\setuptools\__init__.py",
line 129, in setup
      return distutils.core.setup(**attrs)
    File "f:\program files\anaconda3\lib\distutils\core.py", line 148, in setup
      dist.run_commands()
    File "f:\program files\anaconda3\lib\distutils\dist.py", line 955, in run_co
mmands
      self.run_command(cmd)
    File "f:\program files\anaconda3\lib\distutils\dist.py", line 974, in run_co
mmand
      cmd_obj.run()
    File "f:\program files\anaconda3\lib\site-packages\wheel\bdist_wheel.py", li
ne 202, in run
      self.run_command('build')
    File "f:\program files\anaconda3\lib\distutils\cmd.py", line 313, in run_com
mand
      self.distribution.run_command(command)
    File "f:\program files\anaconda3\lib\distutils\dist.py", line 974, in run_co
mmand
      cmd_obj.run()
    File "f:\program files\anaconda3\lib\distutils\command\build.py", line 135,
in run
      self.run_command(cmd_name)
    File "f:\program files\anaconda3\lib\distutils\cmd.py", line 313, in run_com
mand
      self.distribution.run_command(command)
    File "f:\program files\anaconda3\lib\distutils\dist.py", line 974, in run_co
mmand
      cmd_obj.run()
    File "C:\Users\ADMINI~1\AppData\Local\Temp\pip-install-z6wr0c9k\dlib\setup.p
y", line 127, in run
      cmake_version = self.get_cmake_version()
    File "C:\Users\ADMINI~1\AppData\Local\Temp\pip-install-z6wr0c9k\dlib\setup.p
y", line 123, in get_cmake_version
      "\n*******************************************************************\n")

  RuntimeError:
  *******************************************************************
   CMake must be installed to build the following extensions: dlib
  *******************************************************************

  ----------------------------------------
  Failed building wheel for dlib
  Running setup.py clean for dlib
Failed to build dlib
Installing collected packages: dlib, face-recognition
  Running setup.py install for dlib ... error
    Complete output from command "f:\program files\anaconda3\python.exe" -u -c "
import setuptools, tokenize;__file__='C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\
\pip-install-z6wr0c9k\\dlib\\setup.py';f=getattr(tokenize, 'open', open)(__file_
_);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'e
xec'))" install --record C:\Users\ADMINI~1\AppData\Local\Temp\pip-record-3xa50wt
q\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    package init file 'dlib\__init__.py' not found (or not a regular file)
    running build_ext
    Traceback (most recent call last):
      File "C:\Users\ADMINI~1\AppData\Local\Temp\pip-install-z6wr0c9k\dlib\setup
.py", line 118, in get_cmake_version
        out = subprocess.check_output(['cmake', '--version'])
      File "f:\program files\anaconda3\lib\subprocess.py", line 626, in check_ou
tput
        **kwargs).stdout
      File "f:\program files\anaconda3\lib\subprocess.py", line 693, in run
        with Popen(*popenargs, **kwargs) as process:
      File "f:\program files\anaconda3\lib\subprocess.py", line 947, in __init__

        restore_signals, start_new_session)
      File "f:\program files\anaconda3\lib\subprocess.py", line 1224, in _execut
e_child
        startupinfo)
    FileNotFoundError: [WinError 2] 系统找不到指定的文件。

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\ADMINI~1\AppData\Local\Temp\pip-install-z6wr0c9k\dlib\setup
.py", line 257, in <module>
        'Topic :: Software Development',
      File "f:\program files\anaconda3\lib\site-packages\setuptools\__init__.py"
, line 129, in setup
        return distutils.core.setup(**attrs)
      File "f:\program files\anaconda3\lib\distutils\core.py", line 148, in setu
p
        dist.run_commands()
      File "f:\program files\anaconda3\lib\distutils\dist.py", line 955, in run_
commands
        self.run_command(cmd)
      File "f:\program files\anaconda3\lib\distutils\dist.py", line 974, in run_
command
        cmd_obj.run()
      File "f:\program files\anaconda3\lib\site-packages\setuptools\command\inst
all.py", line 61, in run
        return orig.install.run(self)
      File "f:\program files\anaconda3\lib\distutils\command\install.py", line 5
39, in run
        self.run_command('build')
      File "f:\program files\anaconda3\lib\distutils\cmd.py", line 313, in run_c
ommand
        self.distribution.run_command(command)
      File "f:\program files\anaconda3\lib\distutils\dist.py", line 974, in run_
command
        cmd_obj.run()
      File "f:\program files\anaconda3\lib\distutils\command\build.py", line 135
, in run
        self.run_command(cmd_name)
      File "f:\program files\anaconda3\lib\distutils\cmd.py", line 313, in run_c
ommand
        self.distribution.run_command(command)
      File "f:\program files\anaconda3\lib\distutils\dist.py", line 974, in run_
command
        cmd_obj.run()
      File "C:\Users\ADMINI~1\AppData\Local\Temp\pip-install-z6wr0c9k\dlib\setup
.py", line 127, in run
        cmake_version = self.get_cmake_version()
      File "C:\Users\ADMINI~1\AppData\Local\Temp\pip-install-z6wr0c9k\dlib\setup
.py", line 123, in get_cmake_version
        "\n*******************************************************************\n
")
    RuntimeError:
    *******************************************************************
     CMake must be installed to build the following extensions: dlib
    *******************************************************************

    ----------------------------------------
Command ""f:\program files\anaconda3\python.exe" -u -c "import setuptools, token
ize;__file__='C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\pip-install-z6wr0c9k\\d
lib\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace
('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record
 C:\Users\ADMINI~1\AppData\Local\Temp\pip-record-3xa50wtq\install-record.txt --s
ingle-version-externally-managed --compile" failed with error code 1 in C:\Users
\ADMINI~1\AppData\Local\Temp\pip-install-z6wr0c9k\dlib\

C:\Users\Administrator>

**Comment by ithjz** [comment]
解决方法https://blog.csdn.net/ArhatShaw/article/details/80201688
